title: Qipo — Documentos legales
description: Política de privacidad y otros documentos legales relacionados con Qipo, app de finanzas personales.
lang: es
baseurl: "/qipo-legal"
url: "https://angel452.github.io"
